services:
  database:
    image: mysql:8.0.28
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: mangila
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  api:
    restart: always
    image: mangila/spring-reactive-r2dbc
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    links:
      - database
    depends_on:
      - database